Update irctc.yml

diff --git a/.github/workflows/irctc.yml b/.github/workflows/irctc.yml
--- a/.github/workflows/irctc.yml
+++ b/.github/workflows/irctc.yml
@@ -31,21 +31,16 @@ jobs:
     - run: |
         sudo timedatectl set-timezone Asia/Kolkata
         pip install -r irctc-captcha-solver/requirements.txt
-        python3 irctc-captcha-solver/app.py "" # python3 irctc-captcha-solver/app.py "" is used for models to load before starting tatkal tickets 
+        python3 irctc-captcha-solver/app.py "" || true # Ensure 'python3' is used and ignore failures if necessary
         PASSWORD=$(jq -r '.inputs.PASSWORD' $GITHUB_EVENT_PATH)
         USERNAME=$(jq -r '.inputs.USERNAME' $GITHUB_EVENT_PATH)
         UPI_ID=$(jq -r '.inputs.UPI_ID' $GITHUB_EVENT_PATH)
-
         echo ::add-mask::$PASSWORD
         echo ::add-mask::$USERNAME
         echo ::add-mask::$UPI_ID
-
         echo PASSWORD=$PASSWORD >> $GITHUB_ENV
         echo USERNAME=$USERNAME >> $GITHUB_ENV
         echo UPI_ID=$UPI_ID >> $GITHUB_ENV
-
-
-    # python3 irctc-captcha-solver/app.py "" is used for models to load before starting tatkal tickets 
 
     - name: Install Node.js and npm
       uses: actions/setup-node@v4
@@ -55,9 +50,5 @@ jobs:
     - name: Installing Cypress & Running IRCTC Cypress Automation
       run: |
         npm install cypress
-        npx cypress run --browser chrome --headed --record --key a15b31a6-b9ee-4678-b9ac-f45a190851fe --env UPI_ID=${{ inputs.UPI_ID || '' }},USERNAME=${{ inputs.USERNAME || secrets.USERNAME }},PASSWORD=${{ inputs.PASSWORD || secrets.PASSWORD }}
-
-    # - name: Running IRCTC Cypress Script
-    #   uses: cypress-io/github-action@v6
-    #   with:
-    #     command: npx cypress run --record --key a15b31a6-b9ee-4678-b9ac-f45a190851fe --env UPI_ID=${{ inputs.UPI_ID || '' }},USERNAME=${{ inputs.USERNAME || secrets.USERNAME }},PASSWORD=${{ inputs.PASSWORD || secrets.PASSWORD }}
+        npx cypress run --browser chrome --headed --record --key a15b31a6-b9ee-4678-b9ac-f45a190851fe \
+        --env UPI_ID=${{ inputs.UPI_ID || '' }},USERNAME=${{ inputs.USERNAME || secrets.USERNAME }},PASSWORD=${{ inputs.PASSWORD || secrets.PASSWORD }}
